CREATE TABLE IF NOT EXISTS `shopItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` varchar(50) NOT NULL DEFAULT '',
	`typeId` varchar(50) NOT NULL DEFAULT '',
	`typeName` varchar(100) NOT NULL DEFAULT '',
	`typeHashName` varchar(200) NOT NULL DEFAULT '',
	`weaponId` int NOT NULL DEFAULT 0,
	`weaponHashName` varchar(200) NOT NULL DEFAULT '',
	`templateHashName` varchar(200) NOT NULL DEFAULT '',
	`templateName` varchar(300) NOT NULL DEFAULT '',
	`iconUrl` varchar(500) NOT NULL DEFAULT '',
	`exteriorName` varchar(100) NOT NULL DEFAULT '',
	`rarityName` varchar(100) NOT NULL DEFAULT '',
	`minSellPrice` decimal(15,2) NOT NULL DEFAULT '0.00',
	`fastShippingMinSellPrice` decimal(15,2) NOT NULL DEFAULT '0.00',
	`referencePrice` decimal(15,2) NOT NULL DEFAULT '0.00',
	`sellNum` int NOT NULL DEFAULT 0,
	`enabled` tinyint NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopItems_id` PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `shopOrders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`playerId` int NOT NULL,
	`shopItemId` int NOT NULL,
	`itemName` varchar(300) NOT NULL DEFAULT '',
	`itemIcon` varchar(500) NOT NULL DEFAULT '',
	`payAmount` decimal(15,2) NOT NULL DEFAULT '0.00',
	`status` varchar(30) NOT NULL DEFAULT 'pending',
	`csOrderNo` varchar(100) NOT NULL DEFAULT '',
	`remark` varchar(500) NOT NULL DEFAULT '',
	`createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shopOrders_id` PRIMARY KEY(`id`)
);
