export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  smsApiUrl: process.env.SMS_API_URL ?? "",
  smsAppCode: process.env.SMS_APP_CODE ?? "",
  smsLoginTemplateId: process.env.SMS_LOGIN_TEMPLATE_ID ?? "",
  smsSafePasswordTemplateId: process.env.SMS_SAFE_PASSWORD_TEMPLATE_ID ?? "",
  smsSignId: process.env.SMS_SIGN_ID ?? "",
  smsExpireMinutes: process.env.SMS_EXPIRE_MINUTES ?? "5",
  realNameApiUrl: process.env.REALNAME_API_URL ?? "",
  realNameAppCode: process.env.REALNAME_APP_CODE ?? "",
  // 管理员账号密码（通过环境变量配置，默认备用密码）
  adminAccount: process.env.ADMIN_ACCOUNT ?? "admin",
  adminPassword: process.env.ADMIN_PASSWORD ?? "admin123",
};
